FROM k8s.gcr.io/e2e-test-images/agnhost:2.33
USER root
RUN apk --update add vim wget jq python3 net-tools iperf3 iptables pciutils ethtool tcpdump util-linux && rm -rf /var/cache/apk/*
ENTRYPOINT trap : TERM INT; sleep infinity & wait # Listen for kill signals and exit quickly.
